name: Build Futhark PropProp

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v13

    - name: Build futhark-PropProp tarball
      id: build_futhark_tarball
      run: |
        nix-build --option sandbox false futhark.nix -o futhark.tar.gz
      env:
        NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM: 1

    - name: Upload futhark-PropProp tarball Artifact
      uses: actions/upload-artifact@v7
      with:
        name: futhark-PropProp-nightly-tarball
        path: propprop.tar.gz
        retention-days: 7
